apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-block-test1
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /dev/nvmf
              name: nvmf-volume
      volumes:
        - name: nvmf-volume
          persistentVolume:
            claimName: pvc-example