apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-nvmf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-nvmf-sc
  resources:
    requests:
      storage: 20Gi
      