kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-nvmf-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-nvmf-controller
  template:
    metadata:
      labels:
        app: csi-nvmf-controller
    spec:
      serviceAccount: csi-nvmf-controller-sa
      containers:
        - name:  csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.3.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=2"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.2.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--v=2"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=false"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: csi-nvmf-plugin
          image: nvmfplugin:latest
          imagePullPolicy: "IfNotPresent"
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--IsControllerServer=true"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: volume-map
              mountPath: /var/lib/kubelet/plugins/csi.nvmf.com/volumes
              mountPropagation: "HostToContainer"

      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: volume-map
          hostPath:
            path:  /var/lib/kubelet/plugins/csi.nvmf.com/volumes
            type: DirectoryOrCreate


